services:
  - type: web
    name: sekre-be-2026
    env: php
    buildCommand: cd Backend && composer install --no-dev --optimize-autoloader
    startCommand: cd Backend && php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: true
